/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.perkss.carbonfootprint;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

class SoftwareCarbonIntensityTest {
    @Test
    void someLibraryMethodReturnsTrue() {
        SoftwareCarbonIntensity sci = new SoftwareCarbonIntensity.SCIBuilder()
                .addEmbodiedEmissions(2.0)
                .addEnergyConsumed(2.0)
                .addFunctionalUnit(1)
                .addLocationBasedMarginalCarbonIntensity(2.0)
                .build();

        Assertions.assertTrue(true);
    }

}
